# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
    - master
    - refs/tags/*

pool:
    vmImage: "ubuntu-latest"

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "12.x"
      displayName: "Install Node.js"
    - task: npmAuthenticate@0
      inputs:
          workingFile: ".npmrc"
      displayName: "Npm authenticate"

    - script: |
          npm install
          npm run build
      displayName: "npm install and build"

    - task: CmdLine@2
      inputs:
          script: "rm -rf .git"

    - task: ArchiveFiles@2
      inputs:
          rootFolderOrFile: "$(Build.SourcesDirectory)/"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
          replaceExistingArchive: true
      displayName: "Create zip file"

    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "drop"
          publishLocation: "Container"
      displayName: "Publish build"
