module.exports = {
	name: "Ocean Data Platform JavaScript SDK",
	mode: "file",
	module: "umd",
	target: "ES6",
	exclude: ["**/utils/**/*"],
	out: "./docs/",
	theme: "markdown",
	readme: "none",
	ignoreCompilerErrors: true,
	excludeNotExported: true,
	hideGenerator: true,
	excludePrivate: true,
	excludeProtected: true,
	includeDeclarations: true,
	excludeExternals: true,
};
