import { DataSources, Filters, ISearchResult } from "./DataHubClient";
import { IDataSourceStyling } from "./DataSourceStylingClient";

export const DATA_SOURCES: Array<ISearchResult> = [
	{
		name: "temperature",
		description: "this is the temp",
		source: "mapbox",
		id: "wod-temperature-year-aggregates",
		sourceUrl: "mapbox://oceandatafoundation.1nze98kc",
		tags: ["WOD", "temperature"],
		dataType: DataSources.MapboxVectorTile,
		filters: [Filters.Depth],
		unit: "°C",
	},
	{
		name: "pressure",
		description: "this is the pressure",
		source: "mapbox",
		id: "wod-pressure-aggregates",
		sourceUrl: "mapbox://oceandatafoundation.pressure_aggregates",
		tags: ["WOD", "pressure"],
		dataType: DataSources.MapboxVectorTile,
		filters: [Filters.Depth, Filters.Time],
		unit: "N/A",
	},
	{
		name: "oxygen",
		description: "this is the oxygen",
		source: "mapbox",
		id: "wod-oxygen-aggregates",
		sourceUrl: "mapbox://oceandatafoundation.oxygen_aggregates",
		tags: ["WOD", "oxygen"],
		dataType: DataSources.MapboxVectorTile,
		filters: [Filters.Depth, Filters.Time],
		unit: "ml/l",
	},
	{
		name: "nitrage",
		description: "this is the nitrate",
		source: "mapbox",
		id: "wod-nitrate-aggregates",
		sourceUrl: "mapbox://oceandatafoundation.nitrate_aggregates",
		tags: ["WOD", "nitrate"],
		dataType: DataSources.MapboxVectorTile,
		filters: [Filters.Depth, Filters.Time],
		unit: "µmol/l",
	},
	{
		name: "ph",
		description: "this is the ph",
		source: "mapbox",
		id: "wod-ph-aggregates",
		sourceUrl: "mapbox://oceandatafoundation.ph_aggregates",
		tags: ["WOD", "ph"],
		dataType: DataSources.MapboxVectorTile,
		filters: [Filters.Depth, Filters.Time],
		unit: "µmol/l",
	},
	{
		name: "chlorophyll",
		description: "this is the chlorophyll",
		source: "mapbox",
		id: "wod-chlorophyll-aggregates",
		sourceUrl: "mapbox://oceandatafoundation.chlorophyll_aggregates",
		tags: ["WOD", "chlorophyll"],
		dataType: DataSources.MapboxVectorTile,
		filters: [Filters.Depth, Filters.Time],
		unit: "N/A",
	},
	{
		name: "alkalinity",
		description: "this is the alkalinity",
		source: "mapbox",
		id: "wod-alkalinity-aggregates",
		sourceUrl: "mapbox://oceandatafoundation.alkalinity_aggregates",
		tags: ["WOD", "alkalinity"],
		dataType: DataSources.MapboxVectorTile,
		filters: [Filters.Depth, Filters.Time],
		unit: "N/A",
	},
	{
		name: "phosphate",
		description: "this is the phosphate",
		source: "mapbox",
		id: "wod-phosphate-aggregates",
		sourceUrl: "mapbox://oceandatafoundation.phosphate_aggregates",
		tags: ["WOD", "phosphate"],
		dataType: DataSources.MapboxVectorTile,
		filters: [Filters.Depth, Filters.Time],
		unit: "N/A",
	},
	{
		name: "silicate",
		description: "this is the silicate",
		source: "mapbox",
		id: "wod-silicate-aggregates",
		sourceUrl: "mapbox://oceandatafoundation.silicate_aggregates",
		tags: ["WOD", "silicate"],
		dataType: DataSources.MapboxVectorTile,
		filters: [Filters.Depth, Filters.Time],
		unit: "N/A",
	},
	{
		name: "windfarms",
		description: "these are the windfarms",
		source: "mapbox",
		id: "norwegian-windfarms",
		sourceUrl: "mapbox://oceandatafoundation.6nk4oxtx",
		tags: ["windfarms", "norway"],
		dataType: DataSources.MapboxVectorTile,
	},
	{
		name: "seacables",
		description: "these are the seacables",
		source: "mapbox",
		id: "norwegian-seacables",
		sourceUrl: "mapbox://oceandatafoundation.bz79mnos",
		tags: ["seacables", "norway"],
		dataType: DataSources.MapboxVectorTile,
	},
	{
		name: "economic zones",
		description: "these are the economic zones",
		source: "mapbox",
		id: "economic-zones",
		sourceUrl: "mapbox://oceandatafoundation.382xxha1",
		tags: ["economic zones", "eez"],
		dataType: DataSources.MapboxVectorTile,
	},
];

export const STYLING_DATA_SOURCES: Array<IDataSourceStyling> = [
	{
		dataSourceId: "wod-temperature-year-aggregates",
		type: "circle",
		color: "#58FCD4",
		circleRadius: 3,
		strokeWidth: 1,
		strokeColor: "#ffffff",
	},
	{
		dataSourceId: "wod-pressure-aggregates",
		type: "circle",
		color: "#EBB931",
		circleRadius: 3,
		strokeWidth: 1,
		strokeColor: "#ffffff",
	},
	{
		dataSourceId: "wod-oxygen-aggregates",
		type: "circle",
		color: "#E7862E",
		circleRadius: 3,
		strokeWidth: 1,
		strokeColor: "#ffffff",
	},
	{
		dataSourceId: "wod-nitrate-aggregates",
		type: "circle",
		color: "#555BE3",
		circleRadius: 3,
		strokeWidth: 1,
		strokeColor: "#ffffff",
	},
	{
		dataSourceId: "wod-ph-aggregates",
		type: "circle",
		color: "#FE9FE4",
		circleRadius: 3,
		strokeWidth: 1,
		strokeColor: "#ffffff",
	},
	{
		dataSourceId: "wod-chlorophyll-aggregates",
		type: "circle",
		color: "#78C35E",
		circleRadius: 3,
		strokeWidth: 1,
		strokeColor: "#ffffff",
	},
	{
		dataSourceId: "wod-alkalinity-aggregates",
		type: "circle",
		color: "#0E8484",
		circleRadius: 3,
		strokeWidth: 1,
		strokeColor: "#ffffff",
	},
	{
		dataSourceId: "wod-phosphate-aggregates",
		type: "circle",
		color: "#2DB7F1",
		circleRadius: 3,
		strokeWidth: 1,
		strokeColor: "#ffffff",
	},
	{
		dataSourceId: "wod-silicate-aggregates",
		type: "circle",
		color: "#FB6299",
		circleRadius: 3,
		strokeWidth: 1,
		strokeColor: "#ffffff",
	},
	{
		dataSourceId: "norwegian-windfarms",
		type: "fill",
		color: "#98D5A8",
		opacity: 0.5,
	},
	{
		dataSourceId: "norwegian-seacables",
		type: "line",
		color: "#8CA5EC",
		strokeWidth: 1,
		opacity: 0.5,
	},
	{
		dataSourceId: "economic zones",
		type: "line",
		color: "#16BFF4",
		strokeWidth: 1,
		lineStyle: "dashed",
	},
];
